# Site settings
title: panthar vs. the internet
email: 
description: > # this means to ignore newlines until "baseurl:"
    These are the adventures of a professional computer tamer.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://scruffybob.com/" # the base hostname & protocol for your site
twitter_username: 
github_username: 

# Build settings
markdown: kramdown

exclude: [ README.md, Gemfile, Gemfile.lock, test.rb ]
